# +----------------------------------------------------------------------------+ #
# |                           AuraSkills Main Config                           | #
# |                                                                            | #
# |                    Discord: https://discord.gg/Bh2EZfB                     | #
# |             Source Code: https://github.com/Archy-X/AuraSkills             | #
# |      Config Guide: https://wiki.aurelium.dev/auraskills/main-config        | #
# +----------------------------------------------------------------------------+ #
# Plugin made by Archy

sql:
  enabled: false
  type: mysql
  host: localhost
  port: 3306
  database: auraskills
  username: root
  password: pass
  load_delay: 0
  always_load_on_join: false
  ssl: false
  pool:
    maximum_pool_size: 10
    minimum_idle: 10
    connection_timeout: 5000
    max_lifetime: 1800000
    keepalive_time: 0
default_language: fr
languages:
- en
- es
- fr
- de
- zh-CN
- zh-TW
- pt-BR
- it
- cs
- pl
- uk
- ko
- nl
- ja
- ru
- id
- vi
- tr
- fi
- th
try_detect_client_language: false
hooks:
  HolographicDisplays:
    enabled: false
  DecentHolograms:
    enabled: true
  LuckPerms:
    enabled: true
    use_permission_cache: true
  PlaceholderAPI:
    enabled: true
  ProtocolLib:
    enabled: true
  Slimefun:
    enabled: true
  Towny:
    enabled: true
  Vault:
    enabled: true
  WorldGuard:
    enabled: true
    blocked_regions:
    - Example
    blocked_check_replace_regions:
    - Example
  MythicMobs:
    enabled: true
    handle_damage_increase: true
    handle_damage_reduction: true
    prevent_regular_xp: false
  Nexo:
    enabled: true
action_bar:
  enabled: true          # MODIFIÉ: false → true (meilleur feedback visuel)
  idle: false            # MODIFIÉ: true → false (moins de spam)
  ability: true
  xp: true               # MODIFIÉ: false → true (voir gains XP)
  maxed: true            # MODIFIÉ: false → true (voir compétences maxées)
  update_period: 10      # MODIFIÉ: 5 → 10 (moins de lag)
  round_xp: true         # MODIFIÉ: false → true (plus lisible)
  placeholder_api: true
  use_suffix: true
  format_last: false
  update_async: true     # MODIFIÉ: false → true (performance)
boss_bar:
  enabled: true
  mode: single
  stay_time: 120         # MODIFIÉ: 60 → 120 (plus visible, 2 minutes)
  update_every: 2        # MODIFIÉ: 1 → 2 (moins de lag)
  round_xp: true         # MODIFIÉ: false → true (plus lisible)
  display_maxed: true
  placeholder_api: true
  use_suffix: true
  format:
  - FARMING GREEN PROGRESS
  - FORAGING RED PROGRESS
  - MINING PURPLE PROGRESS
  - FISHING BLUE PROGRESS
  - EXCAVATION YELLOW PROGRESS
  - ARCHERY PINK PROGRESS
  - DEFENSE BLUE PROGRESS
  - FIGHTING RED PROGRESS
  - ENDURANCE PURPLE PROGRESS
  - AGILITY WHITE PROGRESS
  - ALCHEMY PINK PROGRESS
  - ENCHANTING PURPLE PROGRESS
  - SORCERY BLUE PROGRESS
  - HEALING WHITE PROGRESS
  - FORGING YELLOW PROGRESS
  xp_format: '#.#'
  level_xp_format: '0'
  percent_format: '#.#'  # MODIFIÉ: '#.##' → '#.#' (plus simple)
  money_format: '0.00'
  animate_progress: true
jobs:
  enabled: false         # GARDÉ: false (évite inflation or sur serveur vanilla)
  selection:
    require_selection: true
    default_job_limit: 2
    disable_unselected_xp: false
    cooldown_sec: 0
  income:
    use_xp: true
    use_expression: false
    default:
      income_per_xp: 0.1
      expression: 0.1*xp
    use_final_xp: true
    batching:
      enabled: false
      interval_ms: 2000
      display_individual: false
anti_afk:
  enabled: true          # MODIFIÉ: false → true (éviter exploitation)
  logging_enabled: false # MODIFIÉ: true → false (moins de logs)
  log_threshold: min_count*6  # MODIFIÉ: min_count*4 → min_count*6
  checks:
    block_a:
      enabled: true
      min_count: 150     # MODIFIÉ: 100 → 150 (plus strict)
    damage_a:
      enabled: true
      max_distance: 0.5
      min_count: 20      # MODIFIÉ: 15 → 20
    damage_b:
      enabled: true
      min_count: 8       # MODIFIÉ: 5 → 8
    damage_c:
      enabled: true
      min_count: 60      # MODIFIÉ: 40 → 60
    entity_a:
      enabled: true
      max_distance: 0.5
      min_count: 75      # MODIFIÉ: 50 → 75
    entity_b:
      enabled: true
      min_count: 75      # MODIFIÉ: 50 → 75
    entity_c:
      enabled: true
      min_count: 150     # MODIFIÉ: 100 → 150
    fishing_a:
      enabled: true
      min_count: 15      # MODIFIÉ: 10 → 15
enable_roman_numerals: false
damage_holograms:
  enabled: true          # MODIFIÉ: false → true (feedback visuel)
  scaling: true
  decimal:
    display_when_less_than: 1
    max_amount: 1
  offset:
    x: 0.4
    y: 0.4
    z: 0.4
    random:
      enabled: true      # MODIFIÉ: false → true (plus dynamique)
      x_min: -0.3        # MODIFIÉ: -0.5 → -0.3 (moins extrême)
      x_max: 0.3         # MODIFIÉ: 0.5 → 0.3
      y_min: 0
      y_max: 0.2         # MODIFIÉ: 0 → 0.2 (variation verticale)
      z_min: -0.3        # MODIFIÉ: -0.5 → -0.3
      z_max: 0.3         # MODIFIÉ: 0.5 → 0.3
  colors:
    default: gray
    critical:
      digits:
      - white
      - yellow
      - gold
      - red
      - dark_red
      - dark_purple
      - light_purple
      - blue
      - dark_blue
leaderboards:
  update_period: 12000   # MODIFIÉ: 6000 → 12000 (10min → 20min, moins de lag)
  update_delay: 12000    # MODIFIÉ: 6000 → 12000
start_level: 0
enable_skill_commands: true
check_block_replace:
  enabled: true
  blocked_worlds:
  - Example
blocked_worlds:
- Example
disabled_worlds:
- Example
disable_in_creative_mode: false
data_validation:
  correct_over_max_level: false
on_death:
  reset_skills: false
  reset_xp: false
auto_save:
  enabled: true
  interval_ticks: 6000   # MODIFIÉ: 12000 → 6000 (10min → 5min, plus sécurisé)
leveler:
  title:
    enabled: true
    fade_in: 10          # MODIFIÉ: 5 → 10 (transition plus douce)
    stay: 60             # MODIFIÉ: 80 → 60 (moins long)
    fade_out: 10         # MODIFIÉ: 5 → 10 (transition plus douce)
  sound:
    enabled: true
    type: ENTITY_PLAYER_LEVELUP
    category: MASTER
    volume: 0.7          # MODIFIÉ: 1.0 → 0.7 (moins fort)
    pitch: 0.7           # MODIFIÉ: 0.5 → 0.7 (plus agréable)
  double_check_delay: 20
mana:
  enabled: false
  cooldown_timer_period: 2
modifier:
  armor:
    equip_blocked_materials:
    - EXAMPLE
    timer:
      enabled: true      # MODIFIÉ: false → true (vérifications actives)
      check_period: 5    # MODIFIÉ: 3 → 5 (moins de lag)
  item:
    check_period: 5      # MODIFIÉ: 3 → 5 (moins de lag)
    enable_off_hand: true
  multiplier:
    enabled: true
  auto_convert_from_legacy: false
  temporary:
    enabled: true
    check_period: 40     # MODIFIÉ: 20 → 40 (moins de lag)
requirement:
  enabled: true
  override_global: false
  item:
    prevent_tool_use: true
    prevent_weapon_use: true
    prevent_block_place: true
    prevent_interact: true
    global: []
  armor:
    prevent_armor_equip: true
    global: []
  blocks:
    enabled: true
    bypass_in_creative_mode: true
    bypass_if_op: false
    list: []
damage:
  correct_last_damage: true
critical:
  enabled:
    sword: true
    bow: true
    axe: true
    pickaxe: true
    shovel: true
    hoe: true
    hand: false
    other: false
source:
  grindstone:
    blocked_enchants:
    - blinding_curse
    - vanishing_curse
  statistic:
    gain_period_ticks: 12000
  entity:
    give_alchemy_on_potion_combat: false
menus:
  lore_wrapping_width: 43
  placeholder_api: true
  removal_protection: false
  stats:
    show_trait_values_directly: true
  stat_info:
    enabled: true
loot:
  update_loot_tables: true
  directly_to_inventory: false
check_for_updates: true
automatic_backups:
  enabled: true
  minimum_interval_hours: 24
  max_users: 50000
save_blank_profiles: false
metadata:
  config_migration_complete: false
  file_user_migration_complete: false
  sql_user_migration_complete: false